# Generated by Django 3.1 on 2020-08-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='userid',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='username',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='userpw',
            new_name='user_password',
        ),
    ]
